### ISSUE TITLE
cypress-harness: typing issues with strict mode in Angular

### ISSUE THREAD

**Issue by Badisi** [jscutlery/test-utils#66]
**Package**: @jscutlery/cypress-harness
**Version**: 0.3.4

Using the datepicker example now gives the following ts errors:

<img width="795" alt="Screenshot 2021-06-17 at 21 45 02" src="https://user-images.githubusercontent.com/674862/122462776-4941a080-cfb5-11eb-9105-f8597d32fb30.png">

> Property 'invoke' does not exist on type 'Promise\<MatCalendarHarness>'.
> Property 'selectCell' does not exist on type 'Promise\<MatCalendarHarness>'.
> Property 'should' does not exist on type 'MatCalendarHarness'.

The first two are due to the fact that some material components methods have optional parameters.
Ex : `getCalendar(filter?: CalendarHarnessFilters): Promise<MatCalendarHarness>;`
They can be solved by replacing `(...args: unknown[]) => unknown` with `(...args: any[]) => unknown` in [internals.ts#L7](https://github.com/jscutlery/test-utils/blob/main/packages/cypress-harness/src/lib/internals.ts#L7)

I have not investigated further for the third one..

**Comment by edbzn** [comment]
Hi, I cannot reproduce the errors you describe and tests are passing. Could you elaborate more on how you get this?

**Comment by Badisi** [comment]
### Steps to reproduce

This is what I'm doing: 
```sh
$ ng new cypress-test --routing=true --style=scss
$ cd cypress-test
$ ng add @angular/material --theme="Indigo/Pink" --typography=false --animations=true
> install 12.0.5 : Yes
$ ng add @cypress/schematic --e2eUpdate=true
> install 1.3.1 : Yes
$ npm install -D @jscutlery/cypress-harness cypress-pipe
```
Then:
- Add `import '@jscutlery/cypress-harness/support';` in `cypress/support/index.ts`
- Copy/replace datepicker example in `cypress/integration/spec.ts`
  ```ts
  import { getHarness, getAllHarnesses } from '@jscutlery/cypress-harness';
  import { MatDatepickerInputHarness, MatCalendarHarness } from '@angular/material/datepicker/testing';
  
  describe('datepicker', () => {
      /* getHarness & getAllHarnesses are lazy so you can
       * initialize them wherever you want and reuse them. */
      const datepicker = getHarness(MatDatepickerInputHarness);
      const calendars = getAllHarnesses(MatCalendarHarness);
  
      it('should set date', () => {
          datepicker.setValue('1/1/2010');
          datepicker.openCalendar();
          datepicker.getCalendar().invoke('next'); // next method is already used
          datepicker.getCalendar().selectCell({ text: '10' });
          datepicker.getValue().should('equal', '2/10/2010');
          calendars.should('be.empty');
      });
  });
  ```

### Issue
When opening the project in `vscode` I got the compiler errors in the screenshot above.

**Comment by Badisi** [comment]
@edbzn, you are right on one point though:
Even if `vscode` is complaining, if you try running the tests anyway through cypress, they are executing fine..

**Comment by Badisi** [comment]
When running `@cypress/schematic` it will create a `./cypress/tsconfig.json` which will extends from `./tsconfig.json` (ie. the one from angular). And angular has `compilerOptions.strict` turned on by default.

This is what's causing my issues.

**Comment by Badisi** [comment]
@edbzn, any chance you could look into this any time soon ?
Thanks 🙂

**Comment by edbzn** [comment]
Hi @Badisi, I published a fix for this issue, thanks for reporting!

**Comment by Badisi** [comment]
Hello @edbzn, thanks for the fix !

I can confirm that all the typing issues related to "getHarness" are fixed.

However, the one related to "getAllHarnesses" still exists :
```ts
describe('datepicker', () => {
    const calendars = getAllHarnesses(MatCalendarHarness);
    it('should set date', () => {
        calendars.should('be.empty'); <-- Property 'should' does not exist on type 'Promise<MatCalendarHarness[]>'.
    });
});
```

To fix this : [get-all-harnesses.ts#L8](https://github.com/jscutlery/test-utils/blob/main/packages/cypress-harness/src/lib/get-all-harnesses.ts#L8) -> replace `Promise<HARNESS[]>` with `ChainableHarness<HARNESS[]>`
